% CALCULO DE QUEDA DE TENSÃO EM UM CIRCUITO DE CÂMERAS 
%
% CÁLCULO DE CORRENTE DO CIRCUITO
%
% W1 = POTENCIA TOTAL DO CIRCUITO
% P = POTENCIA DO PAINEL EM WATTS

clc
clear
% PAINEL VAI COM 5 FONTE DE 6W = 30W
P1 = 330 %% (=5 FONTES DE 12VDC X 1 A TEM 0.3A DE CARGA CADA UMA
P2 = 330
P3 = 330
P4 = 330
P5 = 330

W1 = P1+P2+P3+P4+P5

%POTENCIA = TENSAO X CORRENTE, PORTANTO:
%TENSAO = E
%CORRENTE = I 

TENSAO = 220
CORRENTE = W1/TENSAO

%
%
%
%
 
%RESISTENCIA DO MATERIAL (R)
% R-(?Xl)/s
%ONDE ? = CONDUTIVIDADE DO MATERIAL
%l = COMPRIMENTO DO FIO EM KILOMETROS
%s = SECAO DO FIO (DIAMETRO DO FIO)
%

COEFICIENTE = 0.0172
COMPRIMENTO = 490
SECAO = 2.5

R= (COEFICIENTE*COMPRIMENTO)/SECAO

%QUEDA DE TENSAO EM VOLTS (?E) (DELTA E)
% ?E= 2.R X I X COSSENO? (COSSENO DE TETA)
% COSSENO? = 0.8 (80% POR CONVENIENCIA)
COSSENO = 0.80
DOISR = 2*R

DELTAE = DOISR*CORRENTE*COSSENO

QUEDA = TENSAO - DELTAE

% DISTANCIA LINEAR 418 + 5POSTES(SUBIDAS E DESCIDAS)=+-70M= 490M
% QUEDA DE TENSAO EM 150 METROS COM 2.5MM = 208V
% QUEDA DE TENSAO EM 150 METROS COM 4.0MM = 213V
%
% QUEDA DE TENSAO EM 490 METROS COM 2.5MM = 179V
% QUEDA DE TENSAO EM 490 METROS COM 4.0MM = 194V
%
% CIRCUITO MISTO (150MDE4MM + 340MDE2.5 = 184V
%